### ISSUE TITLE
Three GAN papers

### ISSUE THREAD

**Issue by wzirui** [hindupuravinash/the-gan-zoo#38]
[Generating Images with Perceptual Similarity Metrics based on Deep Networks](https://arxiv.org/abs/1602.02644). Maybe call it "DeePSiM" based on the paper?

[DEEP MULTI-SCALE VIDEO PREDICTION BEYOND MEAN SQUARE ERROR](https://arxiv.org/abs/1511.05440). I can't come up with a proper abbreviation. : )

[UNSUPERVISED LEARNING OF VISUAL STRUCTURE USING PREDICTIVE GENERATIVE NETWORKS](https://arxiv.org/abs/1511.06380). Maybe call it "PGN"?

**Comment by hindupuravinash** [comment]
Hello! Sorry for such late reply. Thanks for the paper links and suggestions. Currently, we've been adding papers that have named the GANs themselves rather than us naming them and adding to the list. So, we can wait for the original authors to name them :)

I'll close the issue until then and we can reopen when needed.
